### ISSUE TITLE
Disconnected, suspecting Overlord to be cause

### ISSUE THREAD

**Issue by KamiSami** [The-Fireplace/Overlord#100]
I wrote comment to curse but maybe this site is quickest way to get answers, let me copypaste what i wrote in comments in curse...

 

 Send Message  

 
 
Posted 1 hour ago
 
 
 

I just recently decided to relog from my server and got some weird error in my server log saying: Monstereowing entities threw an error:utterflyGE.namedSpider.namemeCrystal.name

 

My server was working fine earlier without the mod but now i got this, so i was wondering is it from this mod?

 

Edit: It only disconnects me, there are no crashes so i cannot provide crashlog, the error might of might not be from your mod, but this started to happen only after relogging after i downloaded your mod.. No clue if this helps at all...

 

Edit 2: Here is something weird found from client log

[19:32:44] [Netty Client IO #3/ERROR]: There was a critical exception handling a packet on channel overlord
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: index: 14, length: 65 (expected: range(0, 26))

So pretty much the last part of the message, at least, sounds like Overlord is causing some bugs, but i don't know what it means...

**Comment by The-Fireplace** [comment]
Yes, using this issue tracker will get you a faster reaponse than commenting on Curse. I will look in to this as soon as I can.

**Comment by The-Fireplace** [comment]
Yes, using this issue tracker will get you a faster reaponse than commenting on Curse. I will look in to this as soon as I can.

**Comment by The-Fireplace** [comment]
Could you post the entire log on a site such as paste.ubuntu.com and provide me with a link?

**Comment by KamiSami** [comment]
Here you go http://paste.ubuntu.com/24469547/

The client log

**Comment by The-Fireplace** [comment]
Thanks. I see the issue now, I will fix it in version 2.3.5. It should be sometime tonight or tomorrow.

**Comment by KamiSami** [comment]
Thanks :]
