### ISSUE TITLE
Disconnecting still persists

### ISSUE THREAD

**Issue by KamiSami** [The-Fireplace/Overlord#101]
The problem still persists, is it because i am using same world? Do i need to make entirely new world this to work? If interested here is my client log again https://paste.ubuntu.com/24475326/

Sorry for spam, but i need to know if i need to make new world or is there still something to be looked into?

**Comment by The-Fireplace** [comment]
No, using the same world shouldn't be an issue. Thanks for the log, I am trying to find the issue now.

**Comment by The-Fireplace** [comment]
Fixed in 2.3.6

**Comment by KamiSami** [comment]
Thanks for looking into this, i saw that there was update in curse but i do not see new 2.3.6 file in downloads? :S

**Comment by The-Fireplace** [comment]
The file is there, Curse has to approve it before it shows up. Here, go
ahead and get it from the mirror:
https://mods.io/mods/1239-overlord

**Comment by KamiSami** [comment]
Now i can log in again, thank you again for the fix!
