### ISSUE TITLE
Can't build Skeleton Makers

### ISSUE THREAD

**Issue by teebag4lifebro** [The-Fireplace/Overlord#109]
So, first time using this mod. It lets me make the stamp and the ring but won't let me build the skeleton machines. I'm not sure if it's because of other mods I'm using or what. The game doesn't crash or anything, just doesn't show anything when I put in the right combination of stuff to make the skeleton maker.

**Comment by The-Fireplace** [comment]
Would you post a screenshot? And what recipe are you going by, the one in the old guide on the CurseForge/PMC/Minecraft Forum threads? Because it has changed since then, the one in the guide book should be correct, and if not, use JEI and look at what it says.

**Comment by The-Fireplace** [comment]
If this is a valid issue, please provide screenshots and I will re-open it.
