### ISSUE TITLE
[Question] Any chance of skeletal servitors?

### ISSUE THREAD

**Issue by ghost** [The-Fireplace/Overlord#114]
The mod is clearly aimed at undead armies, but I was wondering if there was any chance an aspiring necromancer might be able to set the minions to other tasks like carrying items or harvesting? (I'm looking for alternative automation options.)

**Comment by The-Fireplace** [comment]
Not in the near future. Once I get a path following system implemented, however, this will be more feasible.

**Comment by ghost** [comment]
Ok, thanks.
