### ISSUE TITLE
Milk bottles not healing when thrown 1.12.1-2.4.5

### ISSUE THREAD

**Issue by werff** [The-Fireplace/Overlord#120]
Just that, they don't heal anymore.
If it's a feature it's ok! But last time I tried (in other versions) it worked.

Also, could you make the bucket of milk heal like 4 hp instead of just 1?
I mean, it becomes a chore to heal everyone using their inventories, and milk buckets aren't worth (for that I mean 👍).

Thanks for Reading!

**Comment by The-Fireplace** [comment]
No, it isn't a feature, it's a bug. I'll look in to it soon, I think I know
the cause.

**Comment by werff** [comment]
Thanks!
Could you make the bucket heal more? (Or everything?) Because it takes a lot of work XD

**Comment by werff** [comment]
*a bit more

**Comment by The-Fireplace** [comment]
Make a new issue for that part, I will track it separately.
