### ISSUE TITLE
Sans Mask Crash (Latest Version)

### ISSUE THREAD

**Issue by GoldInvestor1006** [The-Fireplace/Overlord#125]
I crashed when I put on the hidden sans mask.

**Comment by The-Fireplace** [comment]
Will you post your crash report?

**Comment by The-Fireplace** [comment]
Also, what version are you using? "Latest version" is not acceptable, type the version number and the Minecraft version.

**Comment by The-Fireplace** [comment]
Post an actual crash report and I will re-open the issue.
