### ISSUE TITLE
Custom XP Orb performance

### ISSUE THREAD

**Issue by DBotThePony** [The-Fireplace/Overlord#126]
Server's TPS randomly drops to 1 (1 second for one tick loop) and VisualVM displays next profiling snapshot
![d19ba81819_javaw_2017-12-12_19-58-20](https://user-images.githubusercontent.com/6339511/33970573-578ea89c-e0a6-11e7-8c93-f82517dff76e.png)
After 2-3 mins TPS comes back 20, and after 10-15 minutes it drops to 1 again

**Comment by The-Fireplace** [comment]
Lol, whoops. Thanks for letting me know. And thanks for telling me the name of that tool, I'll definitely check it out. For now, though, disabling the config option that allows the custom XP orbs should fix it.

**Comment by DBotThePony** [comment]
Also checkout sampler
https://forum.industrial-craft.net/thread/10820-wip-1-7-10-fastcraft-1-25-note-all-posts-of-new-members-need-to-be-approved-firs/
(spoiler under `Sampler 1.60.1 (MC 1.7.10)/1.62.1 (MC 1.8.9)/1.63.1 (MC 1.9)/1.65.1 (MC 1.9.4)/1.69.3 (MC 1.10)/1.72.1 (MC 1.11)/1.73 (MC 1.12)`)

It generates nps reports which can be opened using VisualVM
And also it provides more clean TPS profiling, because it already filters profiling target (which you need to setup manually in visualvm to cleary know what to profile).
It allows you to profile server easily if it is not on local machine

**Comment by DBotThePony** [comment]
Also i want to request one little thing - could these orbs merge and/or be instantly collected by the player?

**Comment by The-Fireplace** [comment]
Overlord 2.4.9 should resolve this.
