### ISSUE TITLE
[Custom NPCs] Army Skeletons and Custom NPCs won't fight each other

### ISSUE THREAD

**Issue by CostDeath** [The-Fireplace/Overlord#129]
If I start a battle with my skeletons against a Custom NPC they will stand around doing nothing as neither the npc will attack them nor will the skeletons. On the off chance that the npc misses and hits of them though, the 1 skeleton that got hit will start fighting. They will not attack because it hit me in defencive mode nor in agressive mode.

**Comment by CostDeath** [comment]
Does this mean you will try and fix it?

**Comment by The-Fireplace** [comment]
At some point, yes.

**Comment by CostDeath** [comment]
Could you try and do it soonish? (1-2months) I am working on a pack which its idea came from this mod alone. If the mod is not compatible the modpack will suck as i am a fully custom experience of becoming an overlord and to be an overlord, you need an army.

**Comment by The-Fireplace** [comment]
Forge is no longer being supported, and the mod is getting a total rewrite for Fabric. [Here's why](https://gist.github.com/The-Fireplace/d092f25e892a46902ecdec68dee2b938).
