### ISSUE TITLE
Named skinsuit doesn't work

### ISSUE THREAD

**Issue by ghost** [The-Fireplace/Overlord#131]
Overlord-1.12.2-2.4.10
Forge Mod Loader version 14.23.2.2611
client

some log after "[01:47:46] [main/INFO] [FML/]: Forge Mod Loader has successfully loaded 43 mods"

"[01:48:12] [main/TRACE] [overlord/]: Attempting to cache skin for Lalolowka
[01:48:12] [main/WARN] [overlord/]: http://skins.minecraft.net/MinecraftSkins/Lalolowka.png" (i don't know what it means)
nothing happens. It just like steve.

When I use the shears the skin drops in world, inventory of skeleton (the second skin item) and untuchable version on floor (the third).
I use my name with same effect.

my skin is available https://mcskinsearch.com/user/LegendaryInflame

**Comment by ghost** [comment]
I put the png file in cachedImages folder. That's worked. But your skin doesn't supply 64x32 skins. It is broken display.

**Comment by The-Fireplace** [comment]
That's interesting, I've never had any issue getting it to load my skin,
which is 64x64. I'll look in to it.

**Comment by ghost** [comment]
64X32

**Comment by SockWulf** [comment]
Getting the same issue here. Renamed skins don't work unless they are in the cachedImages folder.

**Comment by The-Fireplace** [comment]
That's unusual, I'll have to see if maybe Mojang changes something that
broke my skin retrieval code. Unfortunately, the next time I'll have a
chance to do that is late next month.

**Comment by SockWulf** [comment]
That's not really a problem. People can still use the cachedImages folder method to apply skins in the meantime. Thanks for looking into it though. :)

**Comment by The-Fireplace** [comment]
Alright, I've checked in to it, and it seems Mojang has changed where the skins are stored, as they are now returning error 404. I'll have to find out where they have them now and release an update with the new URL.

**Comment by The-Fireplace** [comment]
Note to self:
https://twitter.com/RiskyKen/status/1033307379780202497
