### ISSUE TITLE
Network write error on dedicated server

### ISSUE THREAD

**Issue by LemADEC** [The-Fireplace/Overlord#133]
As of Guide-API-1.10.2-2.0.3-46.jar and Overlord-1.10.2-2.3.7.jar, player gets disconnected whenever a converted skeleton is in chunk loading for them.

Server console just says
```
[17:46:40] [Server thread/INFO]: LemADEC joined the game
[17:46:42] [Server thread/INFO]: LemADEC lost connection: Internal Exception: java.io.IOException: Error while write(...): Connection reset by peer
[17:46:42] [Server thread/INFO]: LemADEC left the game
```

Client console just says
```
[22:45:59] [Netty Client IO #0/ERROR] [FML/]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException
```

**Comment by The-Fireplace** [comment]
Is there any additional info in fml-server-latest.log when you shut down the server after it happens?

**Comment by LemADEC** [comment]
sadly, no

**Comment by LemADEC** [comment]
I've found logs in the proxy. Apparently, the network packet isn't having the expected meta values, as reported here: https://github.com/HexagonMC/BungeeCord/issues/200
Are the mod entities derived from a vanilla boss mob?

**Comment by The-Fireplace** [comment]
No, my entities aren't derived from a vanilla boss mob. I'm curious to see
what they see, as this issue seems to be bungee's fault, not mine.

**Comment by LemADEC** [comment]
The issue is due to custom data serializer used on entities. The custom nature makes it next to impossible for a proxy to handle it.
