### ISSUE TITLE
Skeletons doing weird things to items on death

### ISSUE THREAD

**Issue by purpleposeidon** [The-Fireplace/Overlord#134]
I started with a skeleton equipped like so:
![image](https://user-images.githubusercontent.com/150333/38547866-13bbc1de-3c65-11e8-8505-5766c09b4151.png)

After a couple rounds of killing the skeleton and putting what it dropped into a new skeleton, this is what I end up with:
![image](https://user-images.githubusercontent.com/150333/38547927-3db30772-3c65-11e8-8f95-69d8f565fd6d.png)

There is an endlessly confused difference between Entity's concept of being dead and EntityLivingBase's. That probably has something to do with items getting duped/destroyed. The damage on the armor might be from vanilla damaging items that mobs drop?

log: https://paste.fedoraproject.org/paste/b5aJtyN81J8rojmcP5BpQw/raw

**Comment by The-Fireplace** [comment]
Try version 2.4.13 and let me know if this is still an issue.

**Comment by purpleposeidon** [comment]
![screenshot_20180923_141106](https://user-images.githubusercontent.com/150333/45933016-837fcf80-bf3a-11e8-864d-064c8cbd0486.png)

Same setup as before. It looks like an improvement though! There's an array on Entity/subclass somewhere that says if the item was picked up off the ground. If it was, then it drops the exact item without any %chance/damage nonsense.

**Comment by The-Fireplace** [comment]
Forge is no longer being supported, and the mod is getting a total rewrite for Fabric. [Here's why](https://gist.github.com/The-Fireplace/d092f25e892a46902ecdec68dee2b938).
