### ISSUE TITLE
[Animania] Add support for milk from Animania

### ISSUE THREAD

**Issue by Sunconure11** [The-Fireplace/Overlord#138]
Animania has several different milk variants. Would it be possible to add support for these in a future update, so that one can use them for crafting your minions?

**Comment by The-Fireplace** [comment]
I've worked with the author of Animania in the past to try getting support
for their milk, and I don't recall ever getting a clear answer about if it
was done. It is closed source, too, so I can't do anything on my end to
make this work. Talk to Animania's author.

**Comment by Sunconure11** [comment]
Actually, they open sourced recently.

https://github.com/capnkirok/animaniamod

**Comment by The-Fireplace** [comment]
Oh, cool. It'll be a few months, but I'll get this done when I get the
chance.

**Comment by The-Fireplace** [comment]
Forge is no longer being supported, and the mod is getting a total rewrite for Fabric. [Here's why](https://gist.github.com/The-Fireplace/d092f25e892a46902ecdec68dee2b938).
