### ISSUE TITLE
milk compatibility

### ISSUE THREAD

**Issue by kami00en** [The-Fireplace/Overlord#140]
i can't seem to be able to put milk into the skeleton builders, i'm not exactly sure of it, but i'm almost certain some other mod changed either the milk itself or the handling of liquids and buckets in general and Overlord isn't recognizing the milk as it's fluid "fuel" anymore.

**Comment by The-Fireplace** [comment]
What other mods do you have loaded?

**Comment by kami00en** [comment]
right, forgot about that:
AdvancedRocketry
agricraft
AkashicTome
architecturecraft
astikoor
AutoRegLib
Baubles
BetterFps
BiblioCraft
Chameleon
CodeChickenLib
colytra
CombinedPotions
culinaryconstruct
cyberware
Earthworks
EnderStorage
Erebus
extraalchemy
ExtraRails
FenceOverhaul
FluidGenerators
foamfix
GardenStuff
Grim+Pack
Guide-API
Hwyla
iceandfire
ImmersiveEngineering

**Comment by kami00en** [comment]
that's... not all... damn, gonna have to see them all manually, not all's in the log...

in any case, JEI says the milk bucket has been added by tinkers, so i heavily suspect it is the main cause here, perhaps with some help from unidict...

**Comment by kami00en** [comment]
07/29/2018  17:51        11,582,504 AdvancedRocketry-1.12.2-1.4.0-93-universal.jar
07/29/2018  18:38         1,342,279 agricraft-2.12.0-1.12.0-a5.jar
07/29/2018  19:21            43,608 AkashicTome-1.2-10.jar
07/29/2018  18:37           897,626 architecturecraft-1.12-2.68.jar
07/30/2018  00:06            59,693 astikoor-1.0.0.jar
07/29/2018  19:21            84,923 AutoRegLib-1.3-18.jar
08/01/2018  22:17           108,450 Baubles-1.12-1.5.2.jar
07/29/2018  19:23           155,196 BetterFps-1.4.8.jar
07/29/2018  18:32         5,122,856 BiblioCraft[v2.4.5][MC1.12.2].jar
07/29/2018  18:27            96,859 Chameleon-1.12-4.1.3.jar
07/29/2018  17:54           700,157 CodeChickenLib-1.12.2-3.2.1.349-universal.jar
08/01/2018  22:17            82,913 colytra-1.12.2-1.1.0.jar
08/06/2018  00:36            12,972 CombinedPotions-1.12-1.1.jar
07/30/2018  00:19            81,690 culinaryconstruct-1.1.1.jar
08/06/2018  00:39           913,778 cyberware-1.12.2-0.2.10.13.jar
07/30/2018  00:27           705,301 Earthworks-1.12-1.3.6.jar
07/29/2018  18:32           223,227 EnderStorage-1.12.2-2.4.5.135-universal.jar
07/29/2018  19:15        12,597,272 Erebus-1.0.22.jar
07/30/2018  00:30           216,180 extraalchemy-0.3.8.5-release.jar
07/30/2018  00:12            53,565 ExtraRails-1.12-1.3.0.jar
07/29/2018  19:06            40,845 FenceOverhaul-1.3.4.jar
08/06/2018  06:58           196,745 FluidGenerators1-0-3.jar
07/29/2018  19:24           206,359 foamfix-0.9.9.1-1.12.2-anarchy.jar
07/30/2018  00:26           158,782 GardenStuff-1.12-2.1.1.jar
08/06/2018  01:27         6,525,580 Grim+Pack-1.12.2-5.2.12.78.jar
08/06/2018  01:54           168,974 Guide-API-1.12-2.1.6-61.jar
08/04/2018  00:24           453,778 Hwyla-1.8.26-B41_1.12.2.jar
07/29/2018  17:35        12,711,831 iceandfire-1.5.2.jar
07/29/2018  19:23         6,097,870 ImmersiveEngineering-0.12-84.jar
07/29/2018  19:23           906,018 immersivepetroleum-1.12.2-1.1.9.jar
08/01/2018  22:12           858,298 infinitylib-1.12.0.jar
07/30/2018  00:10           467,773 JAOPCA-1.12.2-2.2.8.91.jar
07/30/2018  00:20            43,001 JAOPCAAdditions-1.12.2-2.2.1.9.jar
07/29/2018  18:28           575,409 jei_1.12.2-4.11.0.202.jar
07/30/2018  00:20            18,945 JustEnoughPetroleum-0.1.jar
08/01/2018  22:13           496,220 LibVulpes-1.12.2-0.2.8-36-universal.jar
07/29/2018  19:20           867,352 llibrary-1.7.14-1.12.2.jar
07/29/2018  18:01           860,884 Mantle-1.12-1.3.2.24.jar
08/06/2018  01:53           295,872 MechSoldiers-1.12.2-1.1.6.jar
08/04/2018  02:06            33,622 MmmMmmMmmMmm-1.12-1.14.jar
07/30/2018  00:25            70,754 moartinkers-0.6.0.jar
07/29/2018  16:42            82,455 moon-core+7.0+(1.12).jar
07/29/2018  16:53         8,867,761 NaturalFauna+Mod-1.0.0.jar
07/30/2018  00:31             8,640 nomoreglowingpots-1.0.jar
08/05/2018  23:15            33,549 NoMoreRecipeConflict-0.11(1.12.2).jar
08/06/2018  07:05             5,729 noslimes-1.12.2-1.0.jar
07/29/2018  18:27           470,129 NotEnoughItems-1.12.2-2.4.1.238-universal.jar
08/06/2018  01:39           534,256 Overlord-1.12.2-2.4.10.jar
07/29/2018  18:54           610,245 placeableitems-3.3.jar
08/05/2018  23:27           359,796 plustic-6.5.2.0.jar
07/30/2018  00:07            64,037 RealisticItemDrops-1.2.12.jar
08/06/2018  01:35           306,405 ReWIRED-1.0.3.jar
07/30/2018  00:50         1,308,330 rustic-1.0.6.jar
07/29/2018  18:39           464,802 ShadowMC-1.12-3.8.0.jar
07/30/2018  00:48            24,024 stg-1.12.2-1.2.3.jar
07/29/2018  18:27           596,191 StorageDrawers-1.12.2-5.3.7.jar
08/11/2018  12:36         3,810,539 TConstruct-1.12.2-2.10.1.87.jar
08/06/2018  01:16            44,044 Tinkers'+Addons-1.12.1-1.0.7.jar
07/30/2018  00:55           167,871 TinkersComplement-1.12.2-0.2.3b.jar
08/15/2018  22:33         2,203,794 tinkersdefense-1.4.2.18a.jar
07/29/2018  18:23           178,275 UniDict-1.12.2-2.5f.jar
07/29/2018  19:22         5,401,579 Valkyrien+Warfare+0.9_prerelease_5+[Optimization+Update].jar
07/30/2018  00:44            31,462 WailaHarvestability-mc1.12-1.1.12.jar
07/29/2018  19:20            63,189 WanionLib-1.12.2-1.5.jar
07/30/2018  00:44            83,630 Wawla-1.12.2-2.5.257.jar
07/30/2018  00:10            25,417 WrapUp-1.12-1.1.3.jar
08/12/2018  02:45            79,185 XpHolder-1.0.1-mc1.12.x.jar
07/29/2018  16:43        11,434,158 zawa+-+1.3.2+(1.12.2).jar
07/29/2018  18:31            35,549 [1.12]MoVillages-1.5.4.jar

**Comment by kami00en** [comment]
sorry for the extra junk, copied using command prompt coz it was easier and wasn't at all that patient to delet everything unneeded(very sorry)

**Comment by The-Fireplace** [comment]
Forge is no longer being supported, and the mod is getting a total rewrite for Fabric. [Here's why](https://gist.github.com/The-Fireplace/d092f25e892a46902ecdec68dee2b938).
