### ISSUE TITLE
Suggestion: Neutral skeletons in defensive mode

### ISSUE THREAD

**Issue by mser7** [The-Fireplace/Overlord#145]
If a skeleton is in defensive mode, it should only fight mobs if either a player attack it or it attack the player.

**Comment by The-Fireplace** [comment]
Hmm. Perhaps not with current defensive mode, as that is intended to defend your base from mobs, but I may add another mode with this capability. If I do, the current Defensive mode may be called Defend Area, and the new one would be Defend Player.

**Comment by purpleposeidon** [comment]
I've been using skeletons as bodyguards in the Erebus, using Follow + Defend. They're a bit like a herd of excitable puppies chasing after things 40 blocks away that aren't at all interested in trying to kill me.

**Comment by The-Fireplace** [comment]
"Defensive Mode" is not really a concept in Overlord 3, but I do plan to allow them to do something similar to what you're after.
