### ISSUE TITLE
[Ice and Fire, TiCon] Skeleton doesn't recognize modded bows and arrows

### ISSUE THREAD

**Issue by mser7** [The-Fireplace/Overlord#146]
Tested with TiC ice and fire mods. The skeleton doesnt fire dragon bone bow nor the crossbows. When equipped with stymphalian arrows, which can be fired with a vanilla bow, the skeleton only fires vanilla arrows and not the special arrows, yet still consume the arrows

**Comment by The-Fireplace** [comment]
I'll look into it, but no promises. The bow and crossbow likely don't extend the vanilla bow, which is why they aren't recognized. As for the special arrows, I'd have to look into it to figure out the problem.

**Comment by The-Fireplace** [comment]
Forge is no longer being supported, and the mod is getting a total rewrite for Fabric. [Here's why](https://gist.github.com/The-Fireplace/d092f25e892a46902ecdec68dee2b938).
