### ISSUE TITLE
Skeleton went away into the night and never return

### ISSUE THREAD

**Issue by mser7** [The-Fireplace/Overlord#147]
I tested on a superflat world at night, when in attacking modes the skeleton continuously target another mob after it killed one, and forgot to tp back to player as the result, I suggest make a short delay for the targetting ai, so that tp ai is priorited first if it goes too far. Vanilla wolves has this delay I think

**Comment by The-Fireplace** [comment]
Forge is no longer being supported, and the mod is getting a total rewrite for Fabric. [Here's why](https://gist.github.com/The-Fireplace/d092f25e892a46902ecdec68dee2b938).
