### ISSUE TITLE
Lower the detection range for stationed warrior skeletons

### ISSUE THREAD

**Issue by mser7** [The-Fireplace/Overlord#148]
They usually detect the mob further beyond the range that their bow can reach, should set it to 8, similar to vanilla skeletons bow firing range
https://imgur.com/bC5Rt4D

**Comment by The-Fireplace** [comment]
Note to self: Lower this range, but try to make it detect enemies that are below and in front at a longer range to allow warriors sniping enemies from watchtowers.

**Comment by The-Fireplace** [comment]
Forge is no longer being supported, and the mod is getting a total rewrite for Fabric. [Here's why](https://gist.github.com/The-Fireplace/d092f25e892a46902ecdec68dee2b938).
