### ISSUE TITLE
Skeleton loses AI when switching weapons

### ISSUE THREAD

**Issue by mser7** [The-Fireplace/Overlord#149]
Tested with bow and sword switching, how to replicate:

- Spawn in and equip your warrior with some gears and a bow with some arrows
- Have it on Wander area and offense mode so it can attack mobs
- Click on its GUI when it is attacking, and switch out the bow for a sword, and the skeleton will do nothing and just standstill

**Comment by The-Fireplace** [comment]
Forge is no longer being supported, and the mod is getting a total rewrite for Fabric. [Here's why](https://gist.github.com/The-Fireplace/d092f25e892a46902ecdec68dee2b938).
