### ISSUE TITLE
[Ice and Fire] Army skeletons shouldn't take damage from the dragon strike mechanic

### ISSUE THREAD

**Issue by mser7** [The-Fireplace/Overlord#153]
I tested this with the Ice and Fire mod, and there is a dragon strike mechanic that should deal no damage to tamed mobs like wolves, but it still affect the skeletons. I suspect it has to do with the nbt tags that make them tamed to you

"are you sure they don't just blacklist those specific mobs?" I am sure, I tested with tamed mobs from other mods and they also get ignored.

**Comment by The-Fireplace** [comment]
Forge is no longer being supported, and the mod is getting a total rewrite for Fabric. [Here's why](https://gist.github.com/The-Fireplace/d092f25e892a46902ecdec68dee2b938).
