### ISSUE TITLE
Suggestion: Warrior Skeleton jockeys

### ISSUE THREAD

**Issue by mser7** [The-Fireplace/Overlord#156]
A new order for the skeleton that tell it to scan for any tamed skeleton horses near it, and start mounting the horse, that same order should also tell the skeleton to dismount the horse whenever. I think, when set to follow the player, the cavalry skeleton shouldn't teleport, since the horse itself can't teleport, but instead should detect and follow player as a longer range than walking skeletons

**Comment by The-Fireplace** [comment]
#256 has a few more details on how I envision skeleton horses in this mod.
