### ISSUE TITLE
Make sure the cached skins get updated when needed - possibly on restart

### ISSUE THREAD

**Issue by The-Fireplace** [The-Fireplace/Overlord#167]
Rather than redownloading all cached skins, just check when the skin is initially requested after client start if a new one is available from the skin servers. If so, update.

**Comment by BrainStone** [comment]
Couldn't you just use the built in MC cache?

**Comment by BrainStone** [comment]
Couldn't you just use the built in MC cache?

**Comment by The-Fireplace** [comment]
If I recall correctly, there was a good reason not to. Making sure they
still work if you go offline and load up the world, I think?

**Comment by BrainStone** [comment]
The cache persists instances iirc. I'd give it a try.

**Comment by The-Fireplace** [comment]
I'll give it a try when I update to 1.13, I'm planning to rewrite a lot of
stuff then.

**Comment by The-Fireplace** [comment]
Uses vanilla mechanism for skin loading in Overlord 3
