### ISSUE TITLE
Skeletons with Bows run towards and sometimes melee attack enemies.

### ISSUE THREAD

**Issue by The-Fireplace** [The-Fireplace/Overlord#17]
Them melee attacking enemies when they have bows is because they need an AI update.

**Comment by The-Fireplace** [comment]
@Xalveris Try removing the bow and putting it back, or updating the AI some other way. That will get it to detect the bow and switch to ranged AI. How did you give it the bow initially? Because it should have updated the AI then and switched modes accordingly.

**Comment by Xalveris** [comment]
When it happened, I tried removing the bow and putting it back, swapping it to the off hand, giving it a sword and then the bow again, and none of it worked. I killed it and spawned another one after that.

**Comment by The-Fireplace** [comment]
Alright, thanks. FYI, they won't use weapons in the off hand. The off hand
is almost purely decorative at the moment, the only real use for it being
to make sure the skeleton warrior has arrows and choosing arrow type.
