### ISSUE TITLE
Mobs attacking the air, and not being able to teleport them while doing so

### ISSUE THREAD

**Issue by Menoly45** [The-Fireplace/Overlord#171]
title.

**Comment by The-Fireplace** [comment]
Does this happen when no other mods are loaded?

**Comment by The-Fireplace** [comment]
Forge is no longer being supported, and the mod is getting a total rewrite for Fabric. [Here's why](https://gist.github.com/The-Fireplace/d092f25e892a46902ecdec68dee2b938).
