### ISSUE TITLE
Maker Blocks Won't Accept Milk

### ISSUE THREAD

**Issue by Screeching-Noises** [The-Fireplace/Overlord#172]
The maker block is unable to accept milk. Buckets cannot be placed in the maker block, and pumping milk into the block with other mods results in the tank being completely drained without the maker block intaking any.
Currently on version 1.12.2-2.4.14 of the Overlord mod.

**Comment by The-Fireplace** [comment]
What Forge version?

**Comment by The-Fireplace** [comment]
Forge is no longer being supported, and the mod is getting a total rewrite for Fabric. [Here's why](https://gist.github.com/The-Fireplace/d092f25e892a46902ecdec68dee2b938).
