### ISSUE TITLE
Morph Incompatibility

### ISSUE THREAD

**Issue by MFWalter** [The-Fireplace/Overlord#173]
I have the Morph Mod {https://www.curseforge.com/minecraft/mc-mods/morph} in an instance of Minecraft which also contains Overlord. When I morph into a Skeleton Warrior with a Skin Suit from the overlord mod the server starts throwing a huge fit, https://i.gyazo.com/e8516ed78a0ffcd22ca3d66cd980e056.png .

**Comment by The-Fireplace** [comment]
Forge is no longer being supported, and the mod is getting a total rewrite for Fabric. [Here's why](https://gist.github.com/The-Fireplace/d092f25e892a46902ecdec68dee2b938).
