### ISSUE TITLE
Crash with IC2 Classic

### ISSUE THREAD

**Issue by Phonavis** [The-Fireplace/Overlord#175]
**Describe the bug**
No ref found error with IC2 classic, guessing compat is for EXP but they use the same mod ID, and there's no way to disable

**To Reproduce**
Launch the 2 together.

**Logs/Screenshots/Videos**
https://pastebin.com/NTJ5QBG5

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: [1.12.2]
 - Mod Version: [2.4.14]
- IC2 Classic Version -  [1.5.5.1]
 - Forge (If applicable) [14.23.5.2847]

**Comment by The-Fireplace** [comment]
Forge is no longer being supported, and the mod is getting a total rewrite for Fabric. [Here's why](https://gist.github.com/The-Fireplace/d092f25e892a46902ecdec68dee2b938).
