### ISSUE TITLE
Overlord + IC2 = crash

### ISSUE THREAD

**Issue by LPS0607** [The-Fireplace/Overlord#182]
If you try to start the overlord mod + IC2 classics the game crashes.
I don't know what to do.

**Comment by The-Fireplace** [comment]
You should start by providing the crash report, by pasting it on pastebin.com and providing the link here, and tell me the Overlord version and IC2 version.

**Comment by LPS0607** [comment]
https://pastebin.com/xUvEfLsA
-Overlord-1.12.2-2.4.14
-IC2Classic 1.12-1.5.5.1

**Comment by The-Fireplace** [comment]
This was not designed for use with IC2 Classic, try with the normal IC2 (called Industrial Craft on CF)
