### ISSUE TITLE
Wolves attack skeletons

### ISSUE THREAD

**Issue by platypushasnohat** [The-Fireplace/Overlord#190]
Having a tamed wolf near the skeletons causes them to attack as if they were normal skeletons, the skeletons will then kill the tamed wolf.

 - Minecraft: 1.17.1
 - Mod Version: 3.0.1
 - Fabric API: 0.42.1
 - Fireplace lib 6.0.7

**Comment by The-Fireplace** [comment]
I'm unable to get it to happen unprovoked. However, I do see it happening when I attack one of my skeletons. I'll see about getting this fixed.

**Comment by The-Fireplace** [comment]
Fixed in Overlord 3.0.2
