### ISSUE TITLE
Game crashes when a mob is nearby

### ISSUE THREAD

**Issue by Guiller977** [The-Fireplace/Overlord#198]
**Describe the bug**
So, when a mob (tried with skeletons and zombies) is near my skeleton the game just crashes, also if I try to acces the orders menu it "disconects me from server" even tho im playing singleplayer

**To Reproduce**
Let an enemy mob be nearby

Go to a army skeleton and press the orders menu

**Logs/Screenshots/Videos**
https://paste.ubuntu.com/p/RZn27Y7B7w/

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.16.5
 - Mod Version: 3.0.2
 - Fabric Loader 0.12.5
 - Fabric API 0.37.2

**Comment by The-Fireplace** [comment]
Fixed with Overlord 3.0.3
