### ISSUE TITLE
Crash on Movement mode change

### ISSUE THREAD

**Issue by AlisterGontineac** [The-Fireplace/Overlord#199]
When changing the skeleton's orders to wander game crashes.

1. Go to skeleton's menu
2. Click on orders
3. Click movement
4. Change movement mode to wander
5. Crash
6. Log back in after crash, and skeleton is set to wander so the setting saves but crashes the game

**Logs/Screenshots/Videos**
[Crashy Report.txt](https://github.com/The-Fireplace-Minecraft-Mods/Overlord/files/7581873/Crashy.Report.txt)
[crash-2021-11-22_09.18.45-client.txt](https://github.com/The-Fireplace-Minecraft-Mods/Overlord/files/7581874/crash-2021-11-22_09.18.45-client.txt)

**Versions (please complete the following information, do *NOT* say "latest"):**

- Minecraft: 1.17.1
- Mod Version: 3.0.3
- Fireplace Lib Version: 6.2.0
- Fabric API: [e.g. Fabric API 0.42.1

**Comment by The-Fireplace** [comment]
The crash reports you provided appear to be caused by [Dynamic Surroundings](https://github.com/OreCruncher/DynamicSurroundingsFabric/issues), I suggest reporting it to them.
