### ISSUE TITLE
Suggestion: skeleton off hand

### ISSUE THREAD

**Issue by darklordwonton** [The-Fireplace/Overlord#2]
If a skeleton warrior has an item in their offhand they should right click it (using a fake player) and use the AI they would use if they had a bow, unless it's a shield then they should use it to block attacks.

**Comment by The-Fireplace** [comment]
That's an interesting idea. I see it being useful for more than just bows and shields, too. Other projectiles, modded ranged weapons, and more could potentially be used if I do this. I'll see if I can do that.

**Comment by The-Fireplace** [comment]
Not likely to get done. Would rather have fine tuned AI for each item the skeleton is capable of using for the best experience.
