### ISSUE TITLE
"Pursue Combat Targets" movement option

### ISSUE THREAD

**Issue by The-Fireplace** [The-Fireplace/Overlord#200]
**Is your feature request related to a problem? Please describe.**
It is annoying to have a stationed skeleton wandering out to fight enemies if I want them to stand still and attack with a bow.

**Describe the solution you'd like**
Add an option called "Pursue Combat Targets" (defaulted on) that controls whether they go after enemies while fighting.

**Comment by sheriff1john6** [comment]
This is a good idea.
