### ISSUE TITLE
Multiplayer Log Error Spams And Kicks After Configuring Skeleton Orders

### ISSUE THREAD

**Issue by serioos** [The-Fireplace/Overlord#201]
Minecraft 1.17.1
Overlord-3.0.3+1.17.1
Fireplace-Lib-6.2.0+1.17.1
Fabric-api-0.43.1+1.17
Fabric Loader 12.5

This mod relentlessly spams the log with errors in multiplayer. And every time a client edits their skeleton's orders, they are kicked from the server when they click "save & quit" on the orders menu.

Log errors: https://pastebin.com/WveezreY
Modlist: https://pastebin.com/d3ZLwKPj

**Comment by The-Fireplace** [comment]
Fixed in 3.0.4
