### ISSUE TITLE
Overlord Skeletons won't spawn unless on day 0

### ISSUE THREAD

**Issue by LunexLunertic** [The-Fireplace/Overlord#208]
**Describe the bug**
So, as shown in the video the Skeleton won't spawn in unless it is day 0, I have tried multiple nights even on full moon to see if that was the case, but no, it was because it was not day 0 that the skeleton won't spawn. I am using a Datapack that I made using your tutorial but I have done nothing else to it besides making the spawn recipe different.

This is a callback to when someone was talking about it not working and they tried multiple midnights on Nov. 22 of this year in the comments on the curseforge page.

Here is the video provided to show you the problem:

https://youtu.be/2xJLEYRDawE

And here's my datapack though I don't think it is necessary to provide it I will show it's not tampered with in any other way.

**Versions (please complete the following information, do *NOT* say "latest"):**

- Minecraft: 1.18.1
- Mod Version: 3.1.1+1.18.1
- Fireplace Lib Version: Fireplace-Lib-6.2.2+1.18
- Fabric API: [1.18/1.18.1] Fabric API 0.44.0+1.1

[Easier Skeleton Ritual.zip](https://github.com/The-Fireplace-Minecraft-Mods/Overlord/files/7706732/Easier.Skeleton.Ritual.zip)
8

**Comment by The-Fireplace** [comment]
Thanks for the details, I'll get right on it!

**Comment by The-Fireplace** [comment]
Fixed in 3.1.2
