### ISSUE TITLE
Can't use features in fabric 1.18.2

### ISSUE THREAD

**Issue by arcanius** [The-Fireplace/Overlord#215]
**Describe the bug**
Not sure if this is the right place to post it, but I can't find any recipes nor craft anything related to this mod. I'm on the latest stable Fabric release for Minecraft 1.18.2. My modlist is pretty sparse: besides Overlord and Fireplace-Lib it only has optimization mods and Iris for shaders (mods folder provided in the screenshot section) Perhaps it is a compatibility error?
(The mod is visible on Mod Menu but does not work in-game)

**Logs/Screenshots/Videos**
![image](https://user-images.githubusercontent.com/94972041/161441025-6d8cd550-365e-4e72-8065-1ae82907146b.png)

**Versions (please complete the following information, do *NOT* say "latest"):**

- Minecraft: 1.18.2
- Mod Version: 3.1.3
- Fireplace Lib Version: 6.3.1
- Fabric API: Fabric API 0.48.0+1.18.2

**Comment by arcanius** [comment]
Sorry, I'm stupid.

**Comment by The-Fireplace** [comment]
For future reference, what was the issue?

**Comment by arcanius** [comment]
Just me reading the mod description wrong. The casket's supposed to use stripped wood block; I was using stripped wood log. I forgot you could make those.
