### ISSUE TITLE
Casket duplication

### ISSUE THREAD

**Issue by rafter613** [The-Fireplace/Overlord#216]
**Describe the bug**
Breaking a casket can give you back two caskets.

**To Reproduce**
Place down casket (at least Spruce), break the casket with any tool, bare hand, etc, at the "foot" of the casket, ie, the block furthest away from you when you place it down. Two caskets drop.

**Versions (please complete the following information, do *NOT* say "latest"):**

- Minecraft: [e.g. 1.18.1]
- Mod Version: [e.g. 3.1.3+]
- Fireplace Lib Version: [e.g. 6.3.0+1.18.2]
- Fabric API: [e.g. Fabric API 0.46.6 ]

**Comment by The-Fireplace** [comment]
Are you able to actually pick up both caskets? Or only one of the two?

**Comment by rafter613** [comment]
Both caskets get picked up, yeah. Nothing inside the casket seems to be duplicated, just the casket itself.

**Comment by The-Fireplace** [comment]
Fixed in 3.1.4
