### ISSUE TITLE
Skeletons won't spawn

### ISSUE THREAD

**Issue by rafter613** [The-Fireplace/Overlord#217]
**Describe the bug**
Cannot spawn skeletons.
Tried: Setting time to 0, all orientations of caskets and markers, using tombstones or markers, placing items in either end of casket, covering caskets in dirt, dirt path, farmland, or coarse dirt. Tried just milk and bones, and milk + bones, beef, leather, equipment, etc. 
Grave is not covered- can see sky. Tried copying example grave (above ground). Spawn egg summons skeleton normally.  Tried 3.1.3 and 3.1.2. 

Concerned issue might be in following code in AbstractTombstoneBlockEntity.java: 
int dayLength = 24000;
long timeOfDay = world.getTimeOfDay() % dayLength;
return timeOfDay >= 17500 && timeOfDay <= 18500 && (timeOfDay + 100) % 200 == 0;

This sets timeOfDay to the modulus of 24000, which can only be between 0 and 1, then tries to check if timeOfDay is between 17500 and 18500.  

Versions:
    Minecraft: [1.18.1]
    Mod Version: [3.1.3 and 3.1.2]
    Fireplace Lib Version: [6.3.0+1.18.2]
    Fabric API: [Fabric API 0.46.6 ]

**Comment by The-Fireplace** [comment]
That modulus gives the remainder, which we need if timeofday is over 24000.
For example, 36000 % 24000 = 12000

**Comment by The-Fireplace** [comment]
Alright, I've started testing and was able to get one to spawn. Waiting a bit for another to see if it is something weird with the timing. Do you get any errors in the log around the time you'd expect a skeleton to spawn? And do you have any screenshots or a video of your setup?

**Comment by rafter613** [comment]
No errors in the log. Here's a video: https://drive.google.com/file/d/1r9ijb6OOSA7JHJFiqwPDxtmpemDZIGFj/view?usp=sharing
![2022-04-11_22 34 31](https://user-images.githubusercontent.com/90335682/162867950-8fb60a4e-5c1a-4c2f-8714-9adbc3745ddb.png)
![2022-04-11_22 34 34](https://user-images.githubusercontent.com/90335682/162867953-d143ed07-52e8-42d9-ac2a-82b8d45b3091.png)
![2022-04-11_22 34 41](https://user-images.githubusercontent.com/90335682/162867954-a1bdb4f2-46ae-4efc-855e-5367f96ff1ae.png)
![2022-04-11_22 34 48](https://user-images.githubusercontent.com/90335682/162867959-5a6f61ac-4877-4dd8-8c48-78c9fc52465d.png)

**Comment by The-Fireplace** [comment]
Thanks for the video. Your setup looks good, I'll set up something similar and see if I get the same result.
I have to wonder if the modpack is using a different skeleton recipe than the default. I may make an update and make sure it logs if other recipes are present / the default is disabled so we know if that's the cause.

**Comment by rafter613** [comment]
Ah, that's it! I went to the recipe file and it calls for "architects_palette:withered_bone", instead of bones!
