### ISSUE TITLE
Game disconnects, then crashes, when skeletons fight with crossbows

### ISSUE THREAD

**Issue by rafter613** [The-Fireplace/Overlord#218]
**Describe the bug**
Had three skeletons with crossbows, swords, and shields equipped. Encountered a Pillager. When he shot a skeleton, the "connection to the server was lost" (playing singleplayer). Reloaded the game, same thing happened almost immediately. Reloaded again, and quickly killed the pillager. Then the game actually crashed. 
When I took away their crossbows, it worked fine. When returned, fighting a different enemy still caused the crash.
 
**To Reproduce**
Seemingly, just give a skeleton a crossbow,

**Logs/Screenshots/Videos**
Bytebin log of crash: https://bytebin.lucko.me/tpk5VmWNSK
Log report of disconnect: https://pastebin.com/80jVfTci

**Versions (please complete the following information, do *NOT* say "latest"):**

    Minecraft: [e.g. 1.18.1]
    Mod Version: [e.g. 3.1.3+]
    Fireplace Lib Version: [e.g. 6.3.0+1.18.2]
    Fabric API: [e.g. Fabric API 0.46.6 ]

**Comment by The-Fireplace** [comment]
Fixed in 3.1.4

**Comment by rafter613** [comment]
Damn, you're on it! Thank you!
