### ISSUE TITLE
Skeletons not spawning from grave.

### ISSUE THREAD

**Issue by darkspyro92** [The-Fireplace/Overlord#219]
**Describe the bug**
I followed the guide for creating a skeleton and made a grave, but the skeleton isn't spawning. Everything looks right compared to the guide. It's been 3 days and the first skeleton hasn't spawned.

**To Reproduce**
1. Put items in casket.
2. Wait for nothing to happen.

**Logs/Screenshots/Videos**
![image](https://user-images.githubusercontent.com/22324730/163288985-e32acbb6-a8d7-45d6-8831-3cbae4f9e474.png)
![image](https://user-images.githubusercontent.com/22324730/163288994-6e05aa54-508c-4007-ae79-d481dcee8346.png)

**Versions (please complete the following information, do *NOT* say "latest"):**

- Minecraft: 1.18.1
- Mod Version: 3.1.3
- Fireplace Lib Version: 6.3.0
- Fabric API: 0.46.6

**Comment by The-Fireplace** [comment]
Another Quality Modpack 2 uses a custom recipe, not the default. I'll get the wiki updated to reflect that modpacks may change the recipes.
Duplicate of #217
