### ISSUE TITLE
Consistent Client Crash whilst Connected to a Dedicated Server

### ISSUE THREAD

**Issue by CYNO-MC** [The-Fireplace/Overlord#220]
**Describe the bug**
I spawned an Army Skeleton using a spawn egg in Creative Mode, then gave myself a Wand to create a squad. Once I created & assigned the squad, I backed out of the GUI. Once I right clicked back into it with the wand, and clicked "Select Squad", The game immediately crashed client side. After some extensive testing I've determined that _it will crash no matter how you obtain the army skeleton / wand._ 
So long as you create a squad, then attempt to "select squad", client side will collapse into pieces.

> **This doesn't appear to be an issue in Single Player, only when hosted on a server.**

**To Reproduce**
Steps to reproduce the crash:
1. Host Overlord-3.1.4+1.18.2 on a Dedicated Server
2. Summon Army Skeleton (Spawn Egg, Grave-Spawn, etc)
3. Create a Squad & Assign the Squad to the Army Skeleton
4. Exit the GUI & Re-enter it; Then Click "Select Squad"
4. Observe the Client Crash

**Logs/Screenshots/Videos**
[Video](https://www.youtube.com/watch?v=4uGEKK33bVs&ab_channel=CYNO)
[Crash Log](https://gist.github.com/CYNO-MC/a2f4669ba2e940a597a44fdc07e930c4)

**Versions:**
- Minecraft: 1.18.2
- Mod Version: 3.1.4
- Fireplace Lib Version: 6.3.1
- Fabric API: 0.48.0

**Notable Info**
- Doesn't Crash Server
- Fabric API is out of date; Latest release = 0.50.0 on April 10th, 2022
- Crash Log is Consistent

**Comment by The-Fireplace** [comment]
Should be fixed in 3.1.5, try it out and reopen if you still have issues.

**Comment by CYNO-MC** [comment]
Thank you for the fix!
