### ISSUE TITLE
Armor "bug" with the lithium mod

### ISSUE THREAD

**Issue by Doomion** [The-Fireplace/Overlord#222]
While using overlord with the lithium mod the armor values on the skeletons are reduced for example, if you give a full diamond armor to a skeleton, he will only have 3 armor value, meanwhile, without lithium it's 20, which is normal.

Just take a random set of armor and equip it on a skeleton and use some kind of health indicator or something of the sort and you will notice they will have a lower armor value then normal.

(Information at the top left corner)
https://drive.google.com/file/d/1ec_RT4mtOQ7Ukip075n_Ung_PHh5iyYl/view?usp=sharing--------------> Without lithium

https://drive.google.com/file/d/1Z0MRVLxbK8U1gTTmj20D4DQT9wTNPaGH/view?usp=sharing---------> With lithium

- Minecraft:1.18.1
- Mod Version: 3.1.5+
- Fireplace Lib Version: 6.3.1
- Fabric API: 0.46.6

**Comment by The-Fireplace** [comment]
What version of Lithium did you test this with?

**Comment by Doomion** [comment]
version of lithium used: lithium-fabric-mc1.18.1-0.7.8.jar

**Comment by The-Fireplace** [comment]
Thanks! It may be a bit before I can get to it, but there is something you can do in the meantime that should fix it for you and speed up a fix.
https://github.com/CaffeineMC/lithium-fabric/wiki/Configuration-File
In the Lithium config, you can try overriding various options as false one by one until it starts working correctly again. Once you find which it is, let me know and I can get Overlord to make that one false by default.

I would try `mixin.entity.data_tracker.use_arrays` first. If that doesn't do it, you can start by disabling a whole category at a time (`mixin.entity`, `mixin.math`, etc) to find the category then check specific settings in that category.

**Comment by Doomion** [comment]
Im kind of new to this stuff, but I will try to fix it, if im able to fix it I will post a new comment, thanks for the reply and the suggestion.

**Comment by Doomion** [comment]
After a while I found out the problem is in "mixin.entity", when turned to false the values work as intended, but when I tried to find the specific subcategory causing this problem the values would always remain incorrect. I tried to change 1 by 1 the values of each variable, but it just doesn't work and I have no idea why, for now the only solution I can come up with is turning "mixin.entity" in the lithium config to "mixin.entity=false"

**Comment by The-Fireplace** [comment]
Hmm. I wonder if it's some combination of the entity settings then, or something that can't currently be overridden individually

**Comment by The-Fireplace** [comment]
Okay, looking at Lithium, there may be a few more optimizations that aren't documented.
Try `mixin.entity.skip_equipment_change_check=false`

**Comment by Doomion** [comment]
yah, that solved the problem, thanks!

**Comment by The-Fireplace** [comment]
I'm going to leave this open until I fix it from Overlord's side
