### ISSUE TITLE
Errors from client skeletons trying to access the server

### ISSUE THREAD

**Issue by Laifsyn** [The-Fireplace/Overlord#225]
![image](https://user-images.githubusercontent.com/99366187/167283119-81f8f147-ca0b-445e-aa44-657f0e581d6c.png)
It lag spikes(expected because it's erroring) when I try to see another Skeleton entity. Wondering if it's because the skeletons are missing something
Overlord-3.1.5+1.18.2
Fabric 0.14.4

**Comment by Laifsyn** [comment]
It happened in multiplayer(singleplayer not tested)

**Comment by The-Fireplace** [comment]
Please post the waila_errors.log it mentions in the error. And by "another skeleton entity" you mean one that isn't yours or what?

**Comment by Laifsyn** [comment]
[waila_errors.log](https://github.com/The-Fireplace-Minecraft-Mods/Overlord/files/8647523/waila_errors.log)
Entities that I spawned through the Casket. I think I didn't have an issue with the skeletons spawned through spawnegg

When I mean another skeleton entity, is that it will always FPS drop when I change the entity target. Like Look A> FPS Drop> Look B> FPS Drop, Look back to A> FPS drop.

**Comment by Laifsyn** [comment]
Also, I've given them non vanilla armor too(in case it's not reproduceable with vanilla Vanilla armor), specifically [Mythic Metals](https://www.curseforge.com/minecraft/mc-mods/mythicmetals/files)
