### ISSUE TITLE
Is it server-sided or client-sided.

### ISSUE THREAD

**Issue by Smurfboi007** [The-Fireplace/Overlord#235]
Is this mod server-sided or client-sided? Do players need to install it to be able to play? Saw that fireplace Lib for forge was server-sided on 1.18.2, which is what I need.

**Comment by The-Fireplace** [comment]
Players need to install it and Fireplace Lib in order to play. Fireplace Lib can be run as server side only when mods that use it are server side only, but Overlord is required on both sides.
