### ISSUE TITLE
[1.16.5 FABRIC] Crash on server when make a skeleton

### ISSUE THREAD

**Issue by quentin452** [The-Fireplace/Overlord#237]
**Describe the bug**
When you make a skeleton with instructions , the server crash

**To Reproduce**
1. make instruction to make a skeleton
2. crash

**Crash report**

[crash-2022-10-16_23.46.39-server.txt](https://github.com/The-Fireplace-Minecraft-Mods/Overlord/files/9795765/crash-2022-10-16_23.46.39-server.txt)

**Versions (please complete the following information, do *NOT* say "latest"):**

- Minecraft: 1.16.5 fabric
- Mod Version: 3.1.7
- Fireplace Lib Version: 6.3.1
- Fabric API: 0.14.9

**Comment by The-Fireplace** [comment]
Try again with Overlord 3.2.0 and comment if it persists

**Comment by quentin452** [comment]
the crash presist in 3.2.0 and dependencies updated

**Comment by The-Fireplace** [comment]
Can you post the full log file from your crash with Overlord 3.2.0?

**Comment by quentin452** [comment]
[crash-2022-10-23_05.28.05-server.txt](https://github.com/The-Fireplace-Minecraft-Mods/Overlord/files/9845711/crash-2022-10-23_05.28.05-server.txt)
I use local server

**Comment by The-Fireplace** [comment]
I see the problem. Definitely exists in 1.15.2/1.16.5, maybe not in newer versions which is why it was overlooked. Give me a bit and I'll fix it.

**Comment by The-Fireplace** [comment]
Fixed in Overlord 3.2.1
