### ISSUE TITLE
Skeletons won't shoot tipped arrows

### ISSUE THREAD

**Issue by The-Fireplace** [The-Fireplace/Overlord#24]

**Comment by Xalveris** [comment]
Also, the skeleton that I gave it to forgot how to use its bow, even after removing the tipped arrows and giving it normal ones again. It is equipped with an Infinity bow, if that makes a difference.

**Comment by The-Fireplace** [comment]
@Xalveris "Forgets how to use its bow"? As in, it runs towards the enemy and uses melee attacks?

**Comment by Xalveris** [comment]
Yes. It just ran towards a zombie and started melee-ing it with its bow, even though I gave it a normal arrow again.

**Comment by The-Fireplace** [comment]
@Xalveris They shoot tipped arrows just fine, the problem is that it didn't remember to use the bow. We'll continue this discussion on #17 .
