### ISSUE TITLE
Skeletons Unable to be edited and act like zombies

### ISSUE THREAD

**Issue by PasswordTaker** [The-Fireplace/Overlord#240]
### Mod Version

Overlord 3.2.2 MC 1.19.2

### What mod loader(s) are you seeing the problem on?

Fabric

### Problem Description

The Title Describes it all, it happens with both skeletons spawned by a command and by bone/milk casket

### Steps To Reproduce

1. go into the specified version
2. summon a skeleton either by command or casket
3. wait for it to bug
4. you have my problem

**Comment by The-Fireplace** [comment]
Are you using the same account or switching between multiple?

**Comment by The-Fireplace** [comment]
Unable to reproduce. If you are not switching accounts and this happens, comment and provide logs and I can investigate further.
