### ISSUE TITLE
Skeletons not spawning in version 3.2.3

### ISSUE THREAD

**Issue by OMG67** [The-Fireplace/Overlord#242]
I'm using forge and the skeletons are not spawning when using the casket, using 128 bones and 2 buckets of milk, 64 leather and 64 beef, placed the gravestone marker and using 2 soil blocks instead of grass (all of this just to make sure it's not me being dumb).

But it still doesn't summon anything when using time set midnight.

**Comment by The-Fireplace** [comment]
Just to confirm, are you playing with just Overlord or in a modpack? If you're in a modpack, have you checked the recipe in REI to see if they changed it?

**Comment by OMG67** [comment]
I'm playing it on a modpack made by myself, worked until I updated the mod, I've made no modification to the mod yet.

**Comment by The-Fireplace** [comment]
What version did you update from?

**Comment by The-Fireplace** [comment]
And what Minecraft version?

**Comment by OMG67** [comment]
I updated from the last update before this one, so I'm guessing 3.2.2 MC version is 1.18.2 forge

**Comment by The-Fireplace** [comment]
Fixed in Fireplace Lib 7.1.0
