### ISSUE TITLE
Orders dont save

### ISSUE THREAD

**Issue by ATG33** [The-Fireplace/Overlord#243]
### Mod Version

Overlord-Forge-3.2.3+1.19.2.jar

### What mod loader(s) are you seeing the problem on?

Forge

### Mod Loader Version

Forge 1.19.2 - 43.1.7

### Problem Description

When I try to save the orders they get restored to default settings, (I attached a video of said issue) also when I try to create squad it gets stuck on saving squad.
I tried removing all the mods except the necessary ones for Overlord to work, but it did not help

https://user-images.githubusercontent.com/119750673/205452471-69eac316-80c0-4a19-93e9-76936edb385e.mp4

Mod loadout: 
Annotated-DI-Forge-4.0.2+1.19.2
architectury-6.2.46-forge
ars_nouveau-1.19.2-3.4.6
backpacked-2.1.10-1.19
balm-4.5.3
blockui-1.19-0.0.64-ALPHA
cloth-config-8.2.88-forge
configured-1.5.8-1.19
craftable+spawners+fixed
curios-forge-1.19.2-5.1.1.0
domum_ornamentum-1.19-1.0.60-ALPHA-universal
Fireplace-Lib-Forge-7.0.3+1.19.2
framework-0.3.3-1.19
ftb-library-forge-1902.3.9-build.144
ftb-ultimine-forge-1902.3.5-build.65
geckolib-forge-1.19-3.1.18
Guide-API-VP-1.19.2-2.2.4
chestcavity-forge-1.19.2-2.16.2.3
jei-1.19.2-forge-11.3.0.262
material_elements_1.19.2-6.0.0
minecolonies-1.19.2-1.0.1127-BETA
Overlord-Forge-3.2.3+1.19.2
Patchouli-1.19.2-77
portablemobfarm-1.1.2-1.19-1.19.2
simpletomb-1.19-1.0.15
structurize-1.19.2-1.0.452-ALPHA
twilightforest-1.19-4.2.1392-universal
Vampirism-1.19.2-1.9.0-beta.3
waystones-forge-1.19-11.1.0
Xaeros_Minimap_22.15.1_Forge_1.19.1

**Comment by Daikii2** [comment]
I'm with the same problem in 1.19.2 
The option "orders" in skeleton doesn't work.

**Comment by The-Fireplace** [comment]
Fixed with Fireplace Lib 7.1.0
