### ISSUE TITLE
Squads not saving in Forge 19.2

### ISSUE THREAD

**Issue by Elenderion** [The-Fireplace/Overlord#245]
### Mod Version

3.2.3

### What mod loader(s) are you seeing the problem on?

Forge

### Mod Loader Version

MultiMC 5 0.6.16

### Problem Description

When creating squad, I clicked colored blanket, then item for icon, and type in a name.
Then I the click Save and Confirm button. Then it continues to lock the button and when I hover over it, it says "Saving..." for several minutes on end without any stopping. Seems like squad saving is not working.

### Steps To Reproduce

Create squad and try to save it after requirements have been met.

**Comment by Bobthenecromaner** [comment]
I have the samw issue even in the future

**Comment by The-Fireplace** [comment]
Fixed with Fireplace Lib 7.1.0
