### ISSUE TITLE
Cannot open orders menu or create squads

### ISSUE THREAD

**Issue by Matrious** [The-Fireplace/Overlord#247]
### Mod Version

3.2.3

### What mod loader(s) are you seeing the problem on?

Forge

### Mod Loader Version

42.3.4

### Problem Description

I cannot open the orders menu. Ive removed all of my mods and i still cant open it.
I also cannot save squads it just keeps on saying "saving."

### Steps To Reproduce

1.click the skeleton
2.try to create squad
3.click save
4.click order

**Comment by Kymithi** [comment]
I loaded up a fresh install of minecraft with forge version 40.2.14 (MC 1.18.2) and ran into the same issue with mod version 3.2.3. When you click the orders button in the wand, it crashes immediately; regardless of the state of any skeletons or setups around you. The error seems to imply (with my exceedingly limited modding knowledge) that the GUI is failing to open.

**Comment by The-Fireplace** [comment]
Possibly fixed with Fireplace Lib 7.1.0, please let me know.
