### ISSUE TITLE
Register issue

### ISSUE THREAD

**Issue by Auz100** [The-Fireplace/Overlord#260]
### Mod Version

1.17.1

### What mod loader(s) are you seeing the problem on?

Forge

### Problem Description

I need help solving a problem when adding this mod to a multiplayer server. i come across the following message on the Cmd.exe for the mod: 

 

[Server thread/ERROR]: Attempted to register channel overlord:sync_squads even though registry phase is over

[21:07:18] [Server thread/ERROR]: java.lang.IllegalArgumentException: Registration of network channels is locked

 

i have no idea how to solve this but i do know that when i try to create a skeleton nothing shows up and items "specifically the tombstone that i tried" will duplicate if i place them down. 

### Steps To Reproduce

add mod to server mod list
try to follow steps to create skeleton soldier 
place tombstone
error shows up
(error also shows when logging into server)

### Crash Report or Error Logs

```shell
[Server thread/ERROR]: Attempted to register channel overlord:sync_squads even though registry phase is over
[21:12:53] [Server thread/ERROR]: java.lang.IllegalArgumentException: Registration of network channels is locked
```

**Comment by The-Fireplace** [comment]
Fixed with Fireplace Lib 7.1.0
