### ISSUE TITLE
Unable to save squads

### ISSUE THREAD

**Issue by Bobthenecromaner** [The-Fireplace/Overlord#262]
### Mod Version

3.2.3

### What mod loader(s) are you seeing the problem on?

Forge

### Problem Description

Can't seem to save squads when created says saving but doesn't load after that the game its self doesn't freeze I can exit out of that  menu and I can even select different customizations unfortunately I cant get it to work. I have tried all versions of the mod and no luck I have fabric installed and the other 2 mods it says it needs but still no luck..

### Steps To Reproduce

1. Open order wand 
2. Click create squad 
3. Make squad 
4. Hit confirm and save 
5. Sit and wait for 5 years without any progress

### Crash Report or Error Logs

```shell
No crash report
```

**Comment by hamiltoncjames** [comment]
I am experiencing the same problem, i also cant give orders, my assumption is they need to be in a squad first, which doesn't help the issue.

has any solution been provided?

**Comment by The-Fireplace** [comment]
This may be resolved with Fireplace Lib 7.1.0, please give it a try and let me know
