### ISSUE TITLE
Orders glitch still not patched

### ISSUE THREAD

**Issue by Swiper1233** [The-Fireplace/Overlord#263]
### Mod Version

3.2.3

### What mod loader(s) are you seeing the problem on?

Fabric

### Mod Loader Version

0.77.0

### Problem Description

Whenever I try to open the orders menu it crashes my game stating "The game crashed whilst mouseclicked event handler
Error: java.util.NoSuchElementException: No value present" I really want to use this mod but this bug makes it impossible.

### Steps To Reproduce

1. whilst holding the orders staff
2. right click to open the menu 
3. click on orders and the game will crash

### Crash Report or Error Logs

```shell
The game crashed whilst mouseclicked event handler
Error: java.util.NoSuchElementException: No value present
```

**Comment by The-Fireplace** [comment]
Do you have Cloth Config installed?

**Comment by The-Fireplace** [comment]
Closing due to lack of additional info
