### ISSUE TITLE
Augments

### ISSUE THREAD

**Issue by Xalveris** [The-Fireplace/Overlord#33]
I think you should add augments. You would be able to add them onto Skinsuits or the skeleton itself, and it would give it buffs based on the augment. Some examples:

Golden Apple - (slow) Regeneration, like a player's natural regen in 1.8

Enchanted Golden Apple - (fast) Regeneration, like Regen 2 or something. Balanced because Enchanted Golden Apples are so hard to get now.

Iron - +1 armor point (1/2 icon)

Obsidian - +2 armor points (1 icon) and Fire Resistance, but also Slowness to balance it out

Another augment could be a Wither Skull, which would turn the skeleton into a Wither Skeleton so it would apply the wither effect on hit. This could also possibly be an easter egg, if you use the Skeleton Maker in the nether it automatically makes a Wither Skeleton.

**Comment by The-Fireplace** [comment]
I edited out the parts of this comment that are now separate issues.
