### ISSUE TITLE
Log Crash Server (when make skeletons)

### ISSUE THREAD

**Issue by Lightone** [The-Fireplace/Overlord#34]
this happen 2 time while a try apply skins with randon name and the skins is defaults steve but when appear that skin  the game start to freeze but a i kill them and the lag gone, but when try create a skeletons the game crash.

[Crash Log](http://pastebin.com/XDAfXF3M)

**Comment by The-Fireplace** [comment]
Slow down there. It is hard to understand what you're saying. I just tested, and the crash didn't happen to me. Also, there is nothing at all in that crash report to indicate that I am at fault. Have you tried removing Optifine? If it still occurs without Optifine, please, comment on here with a new crash report, and list the steps I can take to cause the crash to happen.
