### ISSUE TITLE
Were These Skeletons Conjured in a Barn?

### ISSUE THREAD

**Issue by DriftRacer14** [The-Fireplace/Overlord#52]
I noticed that, when a skeleton opens a door in order to enter or exit a building, they leave it hanging wide open. Would it be possible to make the Skeletons close the door behind them like villagers do?

![skeletondooropen](https://cloud.githubusercontent.com/assets/19363089/19827681/59fd1fe2-9d80-11e6-90f1-6065394f631d.png)
Door left open by my Skeleton Warrior. Notice how Fence Gates weren't touched.

One issue with this is if a squadron were storming a building each one would open the door, pass through, and slam the door in their comrades faces, so maybe put an option in the GUI for this, or just incorporate it into the various AI types. Stationed wouldn't need to worry about doors, but Follower and Wander Area would each need to go off of the Passive/Defensive/Aggressive setting. Aggressive could leave the door open, whereas Passive and Defensive could make sure the door closes behind them.

As a side issue I don't think Skeletons realize that they can open and pass through fence gates. This is kind of nice, though, because I don't have to worry about my skeleton warriors letting out all my animals.

Personally I feel like it would just be easier to put in another button for door behavior: [Don't] Go Through Doors, [Don't] Open Doors, [Don't] Close Doors, [Don't] Open AND/OR Close Doors, Break Doors Down, Rebuild Doors, etc.

**Comment by The-Fireplace** [comment]
Fence gates, I probably won't do because right now I am using the vanilla door AI, and we don't want them letting animals out, but making it so Defensive and Passive ones close doors behind them, I can do.

**Comment by DriftRacer14** [comment]
A minor annoyance, but I'm glad to hear that it'll be fixed. It's probably for the best that fence gates go ignored.
