### ISSUE TITLE
Just One Byte!... or not?

### ISSUE THREAD

**Issue by DriftRacer14** [The-Fireplace/Overlord#53]
I'm a part-time achievement hunter. When I was going for the "Just One Byte!" achievement (Have a Skeleton Warrior that has consumed 256 Buckets of Milk), I made 32 buckets, stationed my skeleton near my cows, and got to work. Eight times I filled those buckets and shift-clicked them into the Skeleton Warrior's inventory. Eight times the Skeleton Warrior chugged down 32 consecutive buckets of fresh milk. But when he finished the last bucket... nothing. I felt like I'd miscounted so I repeated the 'fill 32 buckets and give them to the warrior' thing two more times and the achievement still failed to fire.

If by 'consumed' the mod means 'He's used this many buckets to 'heal' via 'shift-clicking with bucket in hand'', then I did this wrong, but if I did in fact do this wrong, then I feel that this should be clarified.

If, however, putting a total of 256 milk buckets into the Skeleton Warrior's inventory and pulling a total of 256 empty buckets out of its inventory is indeed supposed to grant this achievement, then I feel that something's gone wrong.

**Comment by The-Fireplace** [comment]
Thanks, I will check it out and see why it isn't working. You are doing it right.

**Comment by The-Fireplace** [comment]
Alright, I found the problem. It will be fixed in 1.3.4.

**Comment by DriftRacer14** [comment]
Thanks for getting to this so quickly. It might not matter to some, but to others this could be a game breaker.
