### ISSUE TITLE
Skeleton Warriors & Baby Skeletons Don't Appear in JourneyMap

### ISSUE THREAD

**Issue by DriftRacer14** [The-Fireplace/Overlord#54]
I was considering adding this to issue #36 but I didn't think that'd be appropriate.

This could potentially be a difficult issue as JourneyMap differentiates between Hostile and Passive/Non-Aggressive mobs, but perhaps this could go off of the 'Passive/Defensive/Aggressive' thing. The Skeleton Warriors don't necessarily need an icon to display in their location indicator, but it would be nice to know where my skeletons are, or at least be able to narrow down my search.

This is a minor issue, and might not be worth fixing; I just thought I'd bring it to attention.

**Comment by The-Fireplace** [comment]
Waiting on a response from Team JourneyMap on how to do this. I expect to see it [here](https://bitbucket.org/TeamJM/journeymap-api/issues/3/making-a-custom-entity-icon-using-the-api).
