### ISSUE TITLE
2.1.1 crashes dedicated Forge 1.11.2 build 2227 on startup randomly

### ISSUE THREAD

**Issue by kreezxil** [The-Fireplace/Overlord#73]
Notes:
     appears to be a random crash, as I restarted the server and this crash didn't occur again

crash report:
https://gist.github.com/2882b1e086613438a8fe48daa179bd1c

fml server latest:
https://gist.github.com/3f30f699d4308cb1732763e9ecd8fbf8

**Comment by The-Fireplace** [comment]
How strange. java.lang.Error. And I see absolutely no reason for this to be happening. Has it happened multiple times?

**Comment by kreezxil** [comment]
So far only that one time

-----Original Message-----

**Comment by The-Fireplace** [comment]
If the issue occurs again with 2.1.2, post the log and I will re-open the issue.
