### ISSUE TITLE
Crash when right-clicking on skeletons

### ISSUE THREAD

**Issue by raydar2016** [The-Fireplace/Overlord#74]
I have only had this issue with baby skeletons (as those are the only ones I have used so far).

I created a baby skeleton, right-clicked and the game crashed.

Please note that I am using quite a few other mods as well and I am using this on a private server for me and my friend. The version is 1.11.2

Here is the crash report:
http://paste.ubuntu.com/24100012/

**Comment by raydar2016** [comment]
Also note that I can only assume this is the correct report. It is the one that showed up. It is the latest crash report I have and this was the last crash I had

**Comment by The-Fireplace** [comment]
Can you upload the fml-client-latest.log?

**Comment by raydar2016** [comment]
Here it is:
http://paste.ubuntu.com/24100013/

**Comment by The-Fireplace** [comment]
Thanks, I'll fix it asap.

**Comment by raydar2016** [comment]
Thank you. I love the Idea of this mod and so I was disappointed when it crashed. Please tell me when it's fixed. :)

**Comment by The-Fireplace** [comment]
Fixed in version 2.1.3.
