### ISSUE TITLE
Crash when joining server

### ISSUE THREAD

**Issue by BSKCraft** [The-Fireplace/Overlord#75]
I get a fatal error connection message when joining my server, this just started and I was able to join once already. Not quite sure what is going on.

No logs in the server only from client.

http://pastebin.com/si3rRN8P

**Comment by The-Fireplace** [comment]
I'll get right on it.

**Comment by The-Fireplace** [comment]
Alright, I may have a solution. I can't test it until tomorrow, though. Sorry for the inconvenience.

**Comment by The-Fireplace** [comment]
Try version 2.2.1, it should fix it. If not, post the new crash report.

**Comment by BSKCraft** [comment]
Just got home and am updating now will let you know.
