### ISSUE TITLE
Overlord commands require op

### ISSUE THREAD

**Issue by greenking13** [The-Fireplace/Overlord#78]
Hello, I'm just here to state that on the latest 1.10.2 version of Overlord, the ally commands are opped only.

**Comment by The-Fireplace** [comment]
Well that's a problem. I'll see what I can do.

**Comment by greenking13** [comment]
I apologize for asking, but will the modification of op-only commands be backported to the latest 1.10.2 version?

**Comment by The-Fireplace** [comment]
Yes, of course. Once users have tested and confirmed that the 1.11.2 version works without issues, I will backport it.
