### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Morph47** [The-Fireplace/Overlord#85]
Hey,
The version Overlord-1.11.2-2.3.1 causes an IndexOutOfBounds Exception and shuts down the internal server. I have changed back to Overlord-1.11.2-2.2.3 and the error disappeared.

Log with Crash Report is attached
would be great if you could look into it with a possible fix

Thanks in advance
 and keep up the great work :)

[mc_crash_report.txt](https://github.com/The-Fireplace/Overlord/files/923644/mc_crash_report.txt)

**Comment by The-Fireplace** [comment]
Thanks for reporting it! I now see the issue, and will release a fix asap.

**Comment by The-Fireplace** [comment]
Fixed in 2.3.2
