### ISSUE TITLE
Skeleton Naming

### ISSUE THREAD

**Issue by Morph47** [The-Fireplace/Overlord#86]
Hey, 

i tried to rename a skeleton with a nametag, but it just opened up the GUI of it
is it possible to rename skeletons that way?
I know that there is the option to show the name of the skinsuit of other Players, but i try to get some i.e. "guards"-flagged skeletons walking around

Any chance you're going to implent a feature like this any time soon or was i just to shortsighted to find it? 

thanks in Advance :)

**Comment by The-Fireplace** [comment]
DI'd you try Sneak+Right Clicking?

**Comment by Morph47** [comment]
No i didnt...
it works perfectly^^
thank you :D
