### ISSUE TITLE
Warriors won't be stationed.

### ISSUE THREAD

**Issue by awkwaRdcaRRot** [The-Fireplace/Overlord#9]
I was just fiddling around with the mod last night and couldn't get the warrior to actually be stationed. They would stay still as long as there was no enemy but as soon as they saw one they would follow them until they were dead and then stay where they kill them. I feel as if stationed and aggressive should allow ranged units to attack but they don't move.

**Comment by The-Fireplace** [comment]
Yes, that is how I want Stationed to be as well. Thanks for reporting this, I will fix it as soon as I can.
